### ISSUE TITLE
Bug: running lib.getGenlFamily in container CentOS using Docker

### ISSUE THREAD

**Issue by renanbastos93** [uber-common/cpustat#29]
So I am using image `FROM centos:7` but when I to try to execute code,  it broke and to generate panic. But when was tried in a VM or UNIX directly it success executing.

Error reference in two lines below:
 - https://github.com/uber-common/cpustat/blob/79c1ebd00ceaea633e818915edc51fc11cbcb67a/lib/netlink.go#L211
 - https://github.com/uber-common/cpustat/blob/79c1ebd00ceaea633e818915edc51fc11cbcb67a/lib/netlink.go#L224

Traceback:
```go
panic: Netlink error code -2 getting TASKSTATS family id

goroutine 1 [running]:
github.com/uber-common/cpustat/lib.getGenlFamily(0xc0000960a0, 0x50da20)
	/root/go/src/github.com/uber-common/cpustat/lib/netlink.go:274 +0x8e
github.com/uber-common/cpustat/lib.NLInit(0x4f04df)
	/root/go/src/github.com/uber-common/cpustat/lib/netlink.go:328 +0x1f3
main.main()
	/test.go:11 +0x34
```

**Comment by vinigfer** [comment]
Could you describe which OS was running on the VM, and the host OS runnign Unix?

**Comment by renanbastos93** [comment]
Yep, I testing in a VM using CentOS 7 on MacOS Catalina, but the problem is in docker
